// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: blast/v1/score/invitational.proto

/* eslint-disable */
import _m0 from "protobufjs/minimal";
import { Timestamp } from "../../../google/protobuf/timestamp";

export const protobufPackage = "blast.v1.score";

/** SSIndividualInvitationalEvent */
export interface SSIndividualInvitationalEvent {
  /**
   * The resource name of SSIndividualInvitationalEvent.
   * Format: invitationals/SSIndividual/events/{event}
   */
  name: string;
  /**
   * target year month.
   * This invitational event is held monthly.
   * iso 8601 format. ex) 2024-02
   */
  yearMonth: string;
  /** The invitational event start date. */
  startDate:
    | string
    | undefined;
  /** The invitational event end date. */
  endDate:
    | string
    | undefined;
  /** The user should write username in discord. */
  formLink: string;
}

/**
 * SSIndividualInvitational
 *
 * @deprecated
 */
export interface SSIndividualInvitational {
  /**
   * The resource name of SSIndividualInvitational.
   * Format: invitationals/SSIndividuals/{invitational}
   */
  name: string;
  /**
   * target year month.
   * This invitational is held monthly.
   * iso 8601 format. ex) 2024-02
   */
  yearMonth: string;
  /** The invitational start date. */
  startDate:
    | string
    | undefined;
  /** The invitational end date. */
  endDate:
    | string
    | undefined;
  /** The user should write username in discord. */
  formLink: string;
}

/** ListSSIndividualInvitationalEventsRequest */
export interface ListSSIndividualInvitationalEventsRequest {
  /** page size */
  pageSize: number;
}

/** ListSSIndividualInvitationalEventsResponse */
export interface ListSSIndividualInvitationalEventsResponse {
  /** The list of SSIndividualInvitationalEvents. */
  invitationalEvents: SSIndividualInvitationalEvent[];
}

/** CreateSSIndividualInvitationalEventRequest */
export interface CreateSSIndividualInvitationalEventRequest {
  /** The SSIndividualInvitationalEvent to create. */
  invitationalEvent: SSIndividualInvitationalEvent | undefined;
}

/**
 * GetSSIndividualInvitationalLetterRequest
 *
 * @deprecated
 */
export interface GetSSIndividualInvitationalLetterRequest {
}

/**
 * SSIndividualInvitationalLetter
 *
 * @deprecated
 */
export interface SSIndividualInvitationalLetter {
  /** invitational */
  invitational: SSIndividualInvitational | undefined;
}

/** InviteSSIndividualInvitationalEventRequest */
export interface InviteSSIndividualInvitationalEventRequest {
  /**
   * The resource name of SSIndividualInvitationalEvent.
   * Format: invitationals/SSIndividual/events/{event}
   */
  invitationalEvent: string;
  /**
   * The list of invitees.
   * Format: users/{user}
   */
  invitees: string[];
  /** letter viewable start time */
  viewableStartTime:
    | string
    | undefined;
  /** letter viewable end time */
  viewableEndTime: string | undefined;
}

/** InviteSSIndividualInvitationalEventResponse */
export interface InviteSSIndividualInvitationalEventResponse {
  /**
   * The resource name of SSIndividualInvitationalEvent.
   * Format: invitationals/SSIndividual/events/{event}
   */
  invitationalEvent: string;
  /**
   * The list of invitees.
   * Format: users/{user}
   */
  invitees: string[];
  /** letter viewable start time */
  viewableStartTime:
    | string
    | undefined;
  /** letter viewable end time */
  viewableEndTime: string | undefined;
}

function createBaseSSIndividualInvitationalEvent(): SSIndividualInvitationalEvent {
  return { name: "", yearMonth: "", startDate: undefined, endDate: undefined, formLink: "" };
}

export const SSIndividualInvitationalEvent = {
  encode(message: SSIndividualInvitationalEvent, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.yearMonth !== "") {
      writer.uint32(18).string(message.yearMonth);
    }
    if (message.startDate !== undefined) {
      Timestamp.encode(toTimestamp(message.startDate), writer.uint32(26).fork()).ldelim();
    }
    if (message.endDate !== undefined) {
      Timestamp.encode(toTimestamp(message.endDate), writer.uint32(34).fork()).ldelim();
    }
    if (message.formLink !== "") {
      writer.uint32(42).string(message.formLink);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SSIndividualInvitationalEvent {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSSIndividualInvitationalEvent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.yearMonth = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.startDate = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.endDate = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.formLink = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SSIndividualInvitationalEvent {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      yearMonth: isSet(object.yearMonth) ? globalThis.String(object.yearMonth) : "",
      startDate: isSet(object.startDate) ? globalThis.String(object.startDate) : undefined,
      endDate: isSet(object.endDate) ? globalThis.String(object.endDate) : undefined,
      formLink: isSet(object.formLink) ? globalThis.String(object.formLink) : "",
    };
  },

  toJSON(message: SSIndividualInvitationalEvent): unknown {
    const obj: any = {};
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.yearMonth !== undefined) {
      obj.yearMonth = message.yearMonth;
    }
    if (message.startDate !== undefined) {
      obj.startDate = message.startDate;
    }
    if (message.endDate !== undefined) {
      obj.endDate = message.endDate;
    }
    if (message.formLink !== undefined) {
      obj.formLink = message.formLink;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SSIndividualInvitationalEvent>, I>>(base?: I): SSIndividualInvitationalEvent {
    return SSIndividualInvitationalEvent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SSIndividualInvitationalEvent>, I>>(
    object: I,
  ): SSIndividualInvitationalEvent {
    const message = createBaseSSIndividualInvitationalEvent();
    message.name = object.name ?? "";
    message.yearMonth = object.yearMonth ?? "";
    message.startDate = object.startDate ?? undefined;
    message.endDate = object.endDate ?? undefined;
    message.formLink = object.formLink ?? "";
    return message;
  },
};

function createBaseSSIndividualInvitational(): SSIndividualInvitational {
  return { name: "", yearMonth: "", startDate: undefined, endDate: undefined, formLink: "" };
}

export const SSIndividualInvitational = {
  encode(message: SSIndividualInvitational, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.yearMonth !== "") {
      writer.uint32(18).string(message.yearMonth);
    }
    if (message.startDate !== undefined) {
      Timestamp.encode(toTimestamp(message.startDate), writer.uint32(26).fork()).ldelim();
    }
    if (message.endDate !== undefined) {
      Timestamp.encode(toTimestamp(message.endDate), writer.uint32(34).fork()).ldelim();
    }
    if (message.formLink !== "") {
      writer.uint32(42).string(message.formLink);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SSIndividualInvitational {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSSIndividualInvitational();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.yearMonth = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.startDate = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.endDate = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 5:
          if (tag !== 42) {
            break;
          }

          message.formLink = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SSIndividualInvitational {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      yearMonth: isSet(object.yearMonth) ? globalThis.String(object.yearMonth) : "",
      startDate: isSet(object.startDate) ? globalThis.String(object.startDate) : undefined,
      endDate: isSet(object.endDate) ? globalThis.String(object.endDate) : undefined,
      formLink: isSet(object.formLink) ? globalThis.String(object.formLink) : "",
    };
  },

  toJSON(message: SSIndividualInvitational): unknown {
    const obj: any = {};
    if (message.name !== undefined) {
      obj.name = message.name;
    }
    if (message.yearMonth !== undefined) {
      obj.yearMonth = message.yearMonth;
    }
    if (message.startDate !== undefined) {
      obj.startDate = message.startDate;
    }
    if (message.endDate !== undefined) {
      obj.endDate = message.endDate;
    }
    if (message.formLink !== undefined) {
      obj.formLink = message.formLink;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SSIndividualInvitational>, I>>(base?: I): SSIndividualInvitational {
    return SSIndividualInvitational.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SSIndividualInvitational>, I>>(object: I): SSIndividualInvitational {
    const message = createBaseSSIndividualInvitational();
    message.name = object.name ?? "";
    message.yearMonth = object.yearMonth ?? "";
    message.startDate = object.startDate ?? undefined;
    message.endDate = object.endDate ?? undefined;
    message.formLink = object.formLink ?? "";
    return message;
  },
};

function createBaseListSSIndividualInvitationalEventsRequest(): ListSSIndividualInvitationalEventsRequest {
  return { pageSize: 0 };
}

export const ListSSIndividualInvitationalEventsRequest = {
  encode(message: ListSSIndividualInvitationalEventsRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.pageSize !== 0) {
      writer.uint32(8).int32(message.pageSize);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ListSSIndividualInvitationalEventsRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListSSIndividualInvitationalEventsRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.pageSize = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListSSIndividualInvitationalEventsRequest {
    return { pageSize: isSet(object.pageSize) ? globalThis.Number(object.pageSize) : 0 };
  },

  toJSON(message: ListSSIndividualInvitationalEventsRequest): unknown {
    const obj: any = {};
    if (message.pageSize !== undefined) {
      obj.pageSize = Math.round(message.pageSize);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListSSIndividualInvitationalEventsRequest>, I>>(
    base?: I,
  ): ListSSIndividualInvitationalEventsRequest {
    return ListSSIndividualInvitationalEventsRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListSSIndividualInvitationalEventsRequest>, I>>(
    object: I,
  ): ListSSIndividualInvitationalEventsRequest {
    const message = createBaseListSSIndividualInvitationalEventsRequest();
    message.pageSize = object.pageSize ?? 0;
    return message;
  },
};

function createBaseListSSIndividualInvitationalEventsResponse(): ListSSIndividualInvitationalEventsResponse {
  return { invitationalEvents: [] };
}

export const ListSSIndividualInvitationalEventsResponse = {
  encode(message: ListSSIndividualInvitationalEventsResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.invitationalEvents) {
      SSIndividualInvitationalEvent.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): ListSSIndividualInvitationalEventsResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListSSIndividualInvitationalEventsResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.invitationalEvents.push(SSIndividualInvitationalEvent.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListSSIndividualInvitationalEventsResponse {
    return {
      invitationalEvents: globalThis.Array.isArray(object?.invitationalEvents)
        ? object.invitationalEvents.map((e: any) => SSIndividualInvitationalEvent.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListSSIndividualInvitationalEventsResponse): unknown {
    const obj: any = {};
    if (message.invitationalEvents?.length) {
      obj.invitationalEvents = message.invitationalEvents.map((e) => SSIndividualInvitationalEvent.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListSSIndividualInvitationalEventsResponse>, I>>(
    base?: I,
  ): ListSSIndividualInvitationalEventsResponse {
    return ListSSIndividualInvitationalEventsResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListSSIndividualInvitationalEventsResponse>, I>>(
    object: I,
  ): ListSSIndividualInvitationalEventsResponse {
    const message = createBaseListSSIndividualInvitationalEventsResponse();
    message.invitationalEvents = object.invitationalEvents?.map((e) => SSIndividualInvitationalEvent.fromPartial(e)) ||
      [];
    return message;
  },
};

function createBaseCreateSSIndividualInvitationalEventRequest(): CreateSSIndividualInvitationalEventRequest {
  return { invitationalEvent: undefined };
}

export const CreateSSIndividualInvitationalEventRequest = {
  encode(message: CreateSSIndividualInvitationalEventRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.invitationalEvent !== undefined) {
      SSIndividualInvitationalEvent.encode(message.invitationalEvent, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): CreateSSIndividualInvitationalEventRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateSSIndividualInvitationalEventRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.invitationalEvent = SSIndividualInvitationalEvent.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateSSIndividualInvitationalEventRequest {
    return {
      invitationalEvent: isSet(object.invitationalEvent)
        ? SSIndividualInvitationalEvent.fromJSON(object.invitationalEvent)
        : undefined,
    };
  },

  toJSON(message: CreateSSIndividualInvitationalEventRequest): unknown {
    const obj: any = {};
    if (message.invitationalEvent !== undefined) {
      obj.invitationalEvent = SSIndividualInvitationalEvent.toJSON(message.invitationalEvent);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateSSIndividualInvitationalEventRequest>, I>>(
    base?: I,
  ): CreateSSIndividualInvitationalEventRequest {
    return CreateSSIndividualInvitationalEventRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateSSIndividualInvitationalEventRequest>, I>>(
    object: I,
  ): CreateSSIndividualInvitationalEventRequest {
    const message = createBaseCreateSSIndividualInvitationalEventRequest();
    message.invitationalEvent = (object.invitationalEvent !== undefined && object.invitationalEvent !== null)
      ? SSIndividualInvitationalEvent.fromPartial(object.invitationalEvent)
      : undefined;
    return message;
  },
};

function createBaseGetSSIndividualInvitationalLetterRequest(): GetSSIndividualInvitationalLetterRequest {
  return {};
}

export const GetSSIndividualInvitationalLetterRequest = {
  encode(_: GetSSIndividualInvitationalLetterRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetSSIndividualInvitationalLetterRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetSSIndividualInvitationalLetterRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): GetSSIndividualInvitationalLetterRequest {
    return {};
  },

  toJSON(_: GetSSIndividualInvitationalLetterRequest): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<GetSSIndividualInvitationalLetterRequest>, I>>(
    base?: I,
  ): GetSSIndividualInvitationalLetterRequest {
    return GetSSIndividualInvitationalLetterRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetSSIndividualInvitationalLetterRequest>, I>>(
    _: I,
  ): GetSSIndividualInvitationalLetterRequest {
    const message = createBaseGetSSIndividualInvitationalLetterRequest();
    return message;
  },
};

function createBaseSSIndividualInvitationalLetter(): SSIndividualInvitationalLetter {
  return { invitational: undefined };
}

export const SSIndividualInvitationalLetter = {
  encode(message: SSIndividualInvitationalLetter, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.invitational !== undefined) {
      SSIndividualInvitational.encode(message.invitational, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SSIndividualInvitationalLetter {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSSIndividualInvitationalLetter();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.invitational = SSIndividualInvitational.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SSIndividualInvitationalLetter {
    return {
      invitational: isSet(object.invitational) ? SSIndividualInvitational.fromJSON(object.invitational) : undefined,
    };
  },

  toJSON(message: SSIndividualInvitationalLetter): unknown {
    const obj: any = {};
    if (message.invitational !== undefined) {
      obj.invitational = SSIndividualInvitational.toJSON(message.invitational);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SSIndividualInvitationalLetter>, I>>(base?: I): SSIndividualInvitationalLetter {
    return SSIndividualInvitationalLetter.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SSIndividualInvitationalLetter>, I>>(
    object: I,
  ): SSIndividualInvitationalLetter {
    const message = createBaseSSIndividualInvitationalLetter();
    message.invitational = (object.invitational !== undefined && object.invitational !== null)
      ? SSIndividualInvitational.fromPartial(object.invitational)
      : undefined;
    return message;
  },
};

function createBaseInviteSSIndividualInvitationalEventRequest(): InviteSSIndividualInvitationalEventRequest {
  return { invitationalEvent: "", invitees: [], viewableStartTime: undefined, viewableEndTime: undefined };
}

export const InviteSSIndividualInvitationalEventRequest = {
  encode(message: InviteSSIndividualInvitationalEventRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.invitationalEvent !== "") {
      writer.uint32(10).string(message.invitationalEvent);
    }
    for (const v of message.invitees) {
      writer.uint32(18).string(v!);
    }
    if (message.viewableStartTime !== undefined) {
      Timestamp.encode(toTimestamp(message.viewableStartTime), writer.uint32(26).fork()).ldelim();
    }
    if (message.viewableEndTime !== undefined) {
      Timestamp.encode(toTimestamp(message.viewableEndTime), writer.uint32(34).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): InviteSSIndividualInvitationalEventRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInviteSSIndividualInvitationalEventRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.invitationalEvent = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.invitees.push(reader.string());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.viewableStartTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.viewableEndTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InviteSSIndividualInvitationalEventRequest {
    return {
      invitationalEvent: isSet(object.invitationalEvent) ? globalThis.String(object.invitationalEvent) : "",
      invitees: globalThis.Array.isArray(object?.invitees) ? object.invitees.map((e: any) => globalThis.String(e)) : [],
      viewableStartTime: isSet(object.viewableStartTime) ? globalThis.String(object.viewableStartTime) : undefined,
      viewableEndTime: isSet(object.viewableEndTime) ? globalThis.String(object.viewableEndTime) : undefined,
    };
  },

  toJSON(message: InviteSSIndividualInvitationalEventRequest): unknown {
    const obj: any = {};
    if (message.invitationalEvent !== undefined) {
      obj.invitationalEvent = message.invitationalEvent;
    }
    if (message.invitees?.length) {
      obj.invitees = message.invitees;
    }
    if (message.viewableStartTime !== undefined) {
      obj.viewableStartTime = message.viewableStartTime;
    }
    if (message.viewableEndTime !== undefined) {
      obj.viewableEndTime = message.viewableEndTime;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InviteSSIndividualInvitationalEventRequest>, I>>(
    base?: I,
  ): InviteSSIndividualInvitationalEventRequest {
    return InviteSSIndividualInvitationalEventRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InviteSSIndividualInvitationalEventRequest>, I>>(
    object: I,
  ): InviteSSIndividualInvitationalEventRequest {
    const message = createBaseInviteSSIndividualInvitationalEventRequest();
    message.invitationalEvent = object.invitationalEvent ?? "";
    message.invitees = object.invitees?.map((e) => e) || [];
    message.viewableStartTime = object.viewableStartTime ?? undefined;
    message.viewableEndTime = object.viewableEndTime ?? undefined;
    return message;
  },
};

function createBaseInviteSSIndividualInvitationalEventResponse(): InviteSSIndividualInvitationalEventResponse {
  return { invitationalEvent: "", invitees: [], viewableStartTime: undefined, viewableEndTime: undefined };
}

export const InviteSSIndividualInvitationalEventResponse = {
  encode(message: InviteSSIndividualInvitationalEventResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.invitationalEvent !== "") {
      writer.uint32(10).string(message.invitationalEvent);
    }
    for (const v of message.invitees) {
      writer.uint32(18).string(v!);
    }
    if (message.viewableStartTime !== undefined) {
      Timestamp.encode(toTimestamp(message.viewableStartTime), writer.uint32(26).fork()).ldelim();
    }
    if (message.viewableEndTime !== undefined) {
      Timestamp.encode(toTimestamp(message.viewableEndTime), writer.uint32(34).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): InviteSSIndividualInvitationalEventResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseInviteSSIndividualInvitationalEventResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.invitationalEvent = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.invitees.push(reader.string());
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.viewableStartTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.viewableEndTime = fromTimestamp(Timestamp.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): InviteSSIndividualInvitationalEventResponse {
    return {
      invitationalEvent: isSet(object.invitationalEvent) ? globalThis.String(object.invitationalEvent) : "",
      invitees: globalThis.Array.isArray(object?.invitees) ? object.invitees.map((e: any) => globalThis.String(e)) : [],
      viewableStartTime: isSet(object.viewableStartTime) ? globalThis.String(object.viewableStartTime) : undefined,
      viewableEndTime: isSet(object.viewableEndTime) ? globalThis.String(object.viewableEndTime) : undefined,
    };
  },

  toJSON(message: InviteSSIndividualInvitationalEventResponse): unknown {
    const obj: any = {};
    if (message.invitationalEvent !== undefined) {
      obj.invitationalEvent = message.invitationalEvent;
    }
    if (message.invitees?.length) {
      obj.invitees = message.invitees;
    }
    if (message.viewableStartTime !== undefined) {
      obj.viewableStartTime = message.viewableStartTime;
    }
    if (message.viewableEndTime !== undefined) {
      obj.viewableEndTime = message.viewableEndTime;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<InviteSSIndividualInvitationalEventResponse>, I>>(
    base?: I,
  ): InviteSSIndividualInvitationalEventResponse {
    return InviteSSIndividualInvitationalEventResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<InviteSSIndividualInvitationalEventResponse>, I>>(
    object: I,
  ): InviteSSIndividualInvitationalEventResponse {
    const message = createBaseInviteSSIndividualInvitationalEventResponse();
    message.invitationalEvent = object.invitationalEvent ?? "";
    message.invitees = object.invitees?.map((e) => e) || [];
    message.viewableStartTime = object.viewableStartTime ?? undefined;
    message.viewableEndTime = object.viewableEndTime ?? undefined;
    return message;
  },
};

/** InvitationalService */
export interface InvitationalService {
  /**
   * ListSSIndividualInvitationals
   * admin
   */
  ListSSIndividualInvitationalEvents(
    request: ListSSIndividualInvitationalEventsRequest,
  ): Promise<ListSSIndividualInvitationalEventsResponse>;
  /**
   * CreateSSIndividualInvitationalEvent
   * admin
   */
  CreateSSIndividualInvitationalEvent(
    request: CreateSSIndividualInvitationalEventRequest,
  ): Promise<SSIndividualInvitationalEvent>;
  /**
   * GetSSIndividualInvitationalLetter
   * Get Active Invitational Letter
   * deprecated: use ListInvitationLetters
   *
   * @deprecated
   */
  GetSSIndividualInvitationalLetter(
    request: GetSSIndividualInvitationalLetterRequest,
  ): Promise<SSIndividualInvitationalLetter>;
  /**
   * InviteSSIndividualInvitationalEvent
   * Send invitations based on past results.
   * for admin, not public api.
   */
  InviteSSIndividualInvitationalEvent(
    request: InviteSSIndividualInvitationalEventRequest,
  ): Promise<InviteSSIndividualInvitationalEventResponse>;
}

export const InvitationalServiceServiceName = "blast.v1.score.InvitationalService";
export class InvitationalServiceClientImpl implements InvitationalService {
  private readonly rpc: Rpc;
  private readonly service: string;
  constructor(rpc: Rpc, opts?: { service?: string }) {
    this.service = opts?.service || InvitationalServiceServiceName;
    this.rpc = rpc;
    this.ListSSIndividualInvitationalEvents = this.ListSSIndividualInvitationalEvents.bind(this);
    this.CreateSSIndividualInvitationalEvent = this.CreateSSIndividualInvitationalEvent.bind(this);
    this.GetSSIndividualInvitationalLetter = this.GetSSIndividualInvitationalLetter.bind(this);
    this.InviteSSIndividualInvitationalEvent = this.InviteSSIndividualInvitationalEvent.bind(this);
  }
  ListSSIndividualInvitationalEvents(
    request: ListSSIndividualInvitationalEventsRequest,
  ): Promise<ListSSIndividualInvitationalEventsResponse> {
    const data = ListSSIndividualInvitationalEventsRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "ListSSIndividualInvitationalEvents", data);
    return promise.then((data) => ListSSIndividualInvitationalEventsResponse.decode(_m0.Reader.create(data)));
  }

  CreateSSIndividualInvitationalEvent(
    request: CreateSSIndividualInvitationalEventRequest,
  ): Promise<SSIndividualInvitationalEvent> {
    const data = CreateSSIndividualInvitationalEventRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "CreateSSIndividualInvitationalEvent", data);
    return promise.then((data) => SSIndividualInvitationalEvent.decode(_m0.Reader.create(data)));
  }

  GetSSIndividualInvitationalLetter(
    request: GetSSIndividualInvitationalLetterRequest,
  ): Promise<SSIndividualInvitationalLetter> {
    const data = GetSSIndividualInvitationalLetterRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "GetSSIndividualInvitationalLetter", data);
    return promise.then((data) => SSIndividualInvitationalLetter.decode(_m0.Reader.create(data)));
  }

  InviteSSIndividualInvitationalEvent(
    request: InviteSSIndividualInvitationalEventRequest,
  ): Promise<InviteSSIndividualInvitationalEventResponse> {
    const data = InviteSSIndividualInvitationalEventRequest.encode(request).finish();
    const promise = this.rpc.request(this.service, "InviteSSIndividualInvitationalEvent", data);
    return promise.then((data) => InviteSSIndividualInvitationalEventResponse.decode(_m0.Reader.create(data)));
  }
}

interface Rpc {
  request(service: string, method: string, data: Uint8Array): Promise<Uint8Array>;
}

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends { $case: string } ? { [K in keyof Omit<T, "$case">]?: DeepPartial<T[K]> } & { $case: T["$case"] }
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function toTimestamp(dateStr: string): Timestamp {
  const date = new globalThis.Date(dateStr);
  const seconds = Math.trunc(date.getTime() / 1_000);
  const nanos = (date.getTime() % 1_000) * 1_000_000;
  return { seconds, nanos };
}

function fromTimestamp(t: Timestamp): string {
  let millis = (t.seconds || 0) * 1_000;
  millis += (t.nanos || 0) / 1_000_000;
  return new globalThis.Date(millis).toISOString();
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
