// Code generated by protoc-gen-fake. DO NOT EDIT.

package profile

import (
	"github.com/ao-labs/protoc-gen-fake/pkg/fake"
)

// Default responses for DailyStarRewardService
var DefaultDailyStarRewardServiceResponses = map[string]fake.Response{
	"/ethereum.v1.profile.DailyStarRewardService/GetDailyStarReward": {
		Method: "/ethereum.v1.profile.DailyStarRewardService/GetDailyStarReward",
		Response: &DailyStarReward{
			Profile:       "fake_Profile",
			CurrentStreak: 42,
			IsClaimable:   true,
			StarReward:    42,
			LastClaim:     nil,
		},
	},
	"/ethereum.v1.profile.DailyStarRewardService/ClaimMyDailyStarReward": {
		Method: "/ethereum.v1.profile.DailyStarRewardService/ClaimMyDailyStarReward",
		Response: &DailyStarReward{
			Profile:       "fake_Profile",
			CurrentStreak: 42,
			IsClaimable:   true,
			StarReward:    42,
			LastClaim:     nil,
		},
	},
}
