# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: onchain/solana/v1/trade.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'onchain/solana/v1/trade.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1donchain/solana/v1/trade.proto\x12\x11onchain.solana.v1\"\xe0\x05\n\x05Trade\x12\x1d\n\nblock_date\x18\x01 \x01(\tR\tblockDate\x12\x1d\n\nblock_time\x18\x02 \x01(\x03R\tblockTime\x12\x1d\n\nblock_slot\x18\x03 \x01(\x04R\tblockSlot\x12\x13\n\x05tx_id\x18\x04 \x01(\tR\x04txId\x12\x16\n\x06signer\x18\x05 \x01(\tR\x06signer\x12!\n\x0cpool_address\x18\x06 \x01(\tR\x0bpoolAddress\x12\x1b\n\tbase_mint\x18\x07 \x01(\tR\x08\x62\x61seMint\x12\x1d\n\nquote_mint\x18\x08 \x01(\tR\tquoteMint\x12\x1d\n\nbase_vault\x18\t \x01(\tR\tbaseVault\x12\x1f\n\x0bquote_vault\x18\n \x01(\tR\nquoteVault\x12\x1f\n\x0b\x62\x61se_amount\x18\x0b \x01(\x01R\nbaseAmount\x12!\n\x0cquote_amount\x18\x0c \x01(\x01R\x0bquoteAmount\x12\x30\n\x14is_inner_instruction\x18\r \x01(\x08R\x12isInnerInstruction\x12+\n\x11instruction_index\x18\x0e \x01(\rR\x10instructionIndex\x12)\n\x10instruction_type\x18\x0f \x01(\tR\x0finstructionType\x12\x36\n\x17inner_instruxtion_index\x18\x10 \x01(\rR\x15innerInstruxtionIndex\x12#\n\router_program\x18\x11 \x01(\tR\x0couterProgram\x12#\n\rinner_program\x18\x12 \x01(\tR\x0cinnerProgram\x12(\n\x10txn_fee_lamports\x18\x13 \x01(\x04R\x0etxnFeeLamports\x12\x34\n\x16signer_lamports_change\x18\x14 \x01(\x03R\x14signerLamportsChangeB>Z<github.com/ao-labs/spacebar-apis/go/onchain/solana/v1;solanab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'onchain.solana.v1.trade_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<github.com/ao-labs/spacebar-apis/go/onchain/solana/v1;solana'
  _globals['_TRADE']._serialized_start=53
  _globals['_TRADE']._serialized_end=789
# @@protoc_insertion_point(module_scope)
