# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pie-dot-fun/v1/auth.proto
# Protobuf Python Version: 6.30.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    1,
    '',
    'pie-dot-fun/v1/auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19pie-dot-fun/v1/auth.proto\x1a google/protobuf/descriptor.proto:O\n\x12gateway_registered\x12\x1e.google.protobuf.MethodOptions\x18\xd1\x86\x03 \x01(\x08R\x11gatewayRegistered:U\n\x15\x61llow_unauthenticated\x12\x1e.google.protobuf.MethodOptions\x18\xd2\x86\x03 \x01(\x08R\x14\x61llowUnauthenticated:<\n\x08\x65xternal\x12\x1e.google.protobuf.MethodOptions\x18\xd3\x86\x03 \x01(\x08R\x08\x65xternal:?\n\nadmin_only\x12\x1e.google.protobuf.MethodOptions\x18\xd4\x86\x03 \x01(\x08R\tadminOnlyB>Z<github.com/ao-labs/spacebar-apis/go/pie-dot-fun/v1;piedotfunb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pie_dot_fun.v1.auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<github.com/ao-labs/spacebar-apis/go/pie-dot-fun/v1;piedotfun'
# @@protoc_insertion_point(module_scope)
