# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ethereum.v1.station import spaceship_pb2 as ethereum_dot_v1_dot_station_dot_spaceship__pb2


class SpaceshipServiceStub(object):
    """SpaceshipService contains the function to interact with the Spaceship of the spacebar
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSpaceships = channel.unary_unary(
                '/ethereum.v1.station.SpaceshipService/ListSpaceships',
                request_serializer=ethereum_dot_v1_dot_station_dot_spaceship__pb2.ListSpaceshipsRequest.SerializeToString,
                response_deserializer=ethereum_dot_v1_dot_station_dot_spaceship__pb2.ListSpaceshipsResponse.FromString,
                )
        self.GetSpaceship = channel.unary_unary(
                '/ethereum.v1.station.SpaceshipService/GetSpaceship',
                request_serializer=ethereum_dot_v1_dot_station_dot_spaceship__pb2.GetSpaceshipRequest.SerializeToString,
                response_deserializer=ethereum_dot_v1_dot_station_dot_spaceship__pb2.Spaceship.FromString,
                )
        self.UpdateSpaceship = channel.unary_unary(
                '/ethereum.v1.station.SpaceshipService/UpdateSpaceship',
                request_serializer=ethereum_dot_v1_dot_station_dot_spaceship__pb2.UpdateSpaceshipRequest.SerializeToString,
                response_deserializer=ethereum_dot_v1_dot_station_dot_spaceship__pb2.Spaceship.FromString,
                )


class SpaceshipServiceServicer(object):
    """SpaceshipService contains the function to interact with the Spaceship of the spacebar
    """

    def ListSpaceships(self, request, context):
        """ListSpaceships will return spaceships.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSpaceship(self, request, context):
        """GetSpaceship
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSpaceship(self, request, context):
        """UpdateSpaceship update Spaceship
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpaceshipServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSpaceships': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSpaceships,
                    request_deserializer=ethereum_dot_v1_dot_station_dot_spaceship__pb2.ListSpaceshipsRequest.FromString,
                    response_serializer=ethereum_dot_v1_dot_station_dot_spaceship__pb2.ListSpaceshipsResponse.SerializeToString,
            ),
            'GetSpaceship': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSpaceship,
                    request_deserializer=ethereum_dot_v1_dot_station_dot_spaceship__pb2.GetSpaceshipRequest.FromString,
                    response_serializer=ethereum_dot_v1_dot_station_dot_spaceship__pb2.Spaceship.SerializeToString,
            ),
            'UpdateSpaceship': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSpaceship,
                    request_deserializer=ethereum_dot_v1_dot_station_dot_spaceship__pb2.UpdateSpaceshipRequest.FromString,
                    response_serializer=ethereum_dot_v1_dot_station_dot_spaceship__pb2.Spaceship.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ethereum.v1.station.SpaceshipService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SpaceshipService(object):
    """SpaceshipService contains the function to interact with the Spaceship of the spacebar
    """

    @staticmethod
    def ListSpaceships(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ethereum.v1.station.SpaceshipService/ListSpaceships',
            ethereum_dot_v1_dot_station_dot_spaceship__pb2.ListSpaceshipsRequest.SerializeToString,
            ethereum_dot_v1_dot_station_dot_spaceship__pb2.ListSpaceshipsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSpaceship(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ethereum.v1.station.SpaceshipService/GetSpaceship',
            ethereum_dot_v1_dot_station_dot_spaceship__pb2.GetSpaceshipRequest.SerializeToString,
            ethereum_dot_v1_dot_station_dot_spaceship__pb2.Spaceship.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateSpaceship(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ethereum.v1.station.SpaceshipService/UpdateSpaceship',
            ethereum_dot_v1_dot_station_dot_spaceship__pb2.UpdateSpaceshipRequest.SerializeToString,
            ethereum_dot_v1_dot_station_dot_spaceship__pb2.Spaceship.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
