// @generated by protoc-gen-es v1.6.0
// @generated from file ethereum/v1/score/score.proto (package ethereum.v1.score, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3, Timestamp } from "@bufbuild/protobuf";

/**
 * @generated from enum ethereum.v1.score.GameMode
 */
export const GameMode = proto3.makeEnum(
  "ethereum.v1.score.GameMode",
  [
    {no: 0, name: "GAME_MODE_UNSPECIFIED"},
    {no: 1, name: "TIME_ATTACK"},
  ],
);

/**
 * @generated from enum ethereum.v1.score.PlayMode
 */
export const PlayMode = proto3.makeEnum(
  "ethereum.v1.score.PlayMode",
  [
    {no: 0, name: "PLAY_MODE_UNSPECIFIED"},
    {no: 1, name: "SINGLE_PLAYER"},
  ],
);

/**
 * CreateScoreRequest
 *
 * @generated from message ethereum.v1.score.CreateScoreRequest
 */
export const CreateScoreRequest = proto3.makeMessageType(
  "ethereum.v1.score.CreateScoreRequest",
  () => [
    { no: 1, name: "score", kind: "message", T: Score },
  ],
);

/**
 * ListScoresRequest payload
 * (-- api-linter: core::0158::request-page-token-field=disabled
 *     aip.dev/not-precedent: We need to do this because reasons. --)
 * (-- api-linter: core::0132::request-unknown-fields=disabled
 *     aip.dev/not-precedent: We really need this field because reasons. --)
 *
 * @generated from message ethereum.v1.score.ListScoresRequest
 */
export const ListScoresRequest = proto3.makeMessageType(
  "ethereum.v1.score.ListScoresRequest",
  () => [
    { no: 1, name: "page_size", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "filter", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "order_by", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * ListScoresResponse response
 * (-- api-linter: core::0158::response-next-page-token-field=disabled
 *     aip.dev/not-precedent: We need to do this because reasons. --)
 *
 * @generated from message ethereum.v1.score.ListScoresResponse
 */
export const ListScoresResponse = proto3.makeMessageType(
  "ethereum.v1.score.ListScoresResponse",
  () => [
    { no: 1, name: "scores", kind: "message", T: Score, repeated: true },
    { no: 2, name: "next_page_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message ethereum.v1.score.GetScoreRequest
 */
export const GetScoreRequest = proto3.makeMessageType(
  "ethereum.v1.score.GetScoreRequest",
  () => [
    { no: 1, name: "score", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message ethereum.v1.score.Score
 */
export const Score = proto3.makeMessageType(
  "ethereum.v1.score.Score",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "profile", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "create_time", kind: "message", T: Timestamp },
    { no: 4, name: "point", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
    { no: 5, name: "game_mode", kind: "enum", T: proto3.getEnumType(GameMode) },
    { no: 6, name: "play_mode", kind: "enum", T: proto3.getEnumType(PlayMode) },
    { no: 7, name: "week", kind: "scalar", T: 13 /* ScalarType.UINT32 */ },
  ],
);

