// @generated by protoc-gen-es v1.6.0
// @generated from file ethereum/v1/outpost/stardoodle.proto (package ethereum.v1.outpost, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum ethereum.v1.outpost.StarDoodleAction
 */
export const StarDoodleAction = proto3.makeEnum(
  "ethereum.v1.outpost.StarDoodleAction",
  [
    {no: 0, name: "TYPE_UNSPECIFIED"},
    {no: 1, name: "DOODLE"},
    {no: 2, name: "MINE"},
  ],
);

/**
 * Request message for ListStarDoodles.
 * If location filter is not specified, the server will return an error.
 *
 * @generated from message ethereum.v1.outpost.ListStarDoodlesRequest
 */
export const ListStarDoodlesRequest = proto3.makeMessageType(
  "ethereum.v1.outpost.ListStarDoodlesRequest",
  () => [
    { no: 1, name: "filter", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * Response message for ListStarDoodles.
 *
 * @generated from message ethereum.v1.outpost.ListStarDoodlesResponse
 */
export const ListStarDoodlesResponse = proto3.makeMessageType(
  "ethereum.v1.outpost.ListStarDoodlesResponse",
  () => [
    { no: 1, name: "star_doodles", kind: "message", T: StarDoodle, repeated: true },
  ],
);

/**
 * StarDoodle message represents the star doodle
 *
 * @generated from message ethereum.v1.outpost.StarDoodle
 */
export const StarDoodle = proto3.makeMessageType(
  "ethereum.v1.outpost.StarDoodle",
  () => [
    { no: 1, name: "doodler", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "location_type", kind: "enum", T: proto3.getEnumType(StarDoodle_LocationType) },
    { no: 3, name: "position", kind: "message", T: Position },
  ],
);

/**
 * @generated from enum ethereum.v1.outpost.StarDoodle.LocationType
 */
export const StarDoodle_LocationType = proto3.makeEnum(
  "ethereum.v1.outpost.StarDoodle.LocationType",
  [
    {no: 0, name: "TYPE_UNSPECIFIED"},
    {no: 1, name: "SQUARE"},
    {no: 2, name: "BACKSPACE"},
  ],
);

/**
 * @generated from message ethereum.v1.outpost.Position
 */
export const Position = proto3.makeMessageType(
  "ethereum.v1.outpost.Position",
  () => [
    { no: 1, name: "x", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
    { no: 2, name: "y", kind: "scalar", T: 5 /* ScalarType.INT32 */ },
  ],
);

/**
 * @generated from message ethereum.v1.outpost.Star
 */
export const Star = proto3.makeMessageType(
  "ethereum.v1.outpost.Star",
  () => [
    { no: 1, name: "color", kind: "enum", T: proto3.getEnumType(Star_StarColor) },
  ],
);

/**
 * @generated from enum ethereum.v1.outpost.Star.StarColor
 */
export const Star_StarColor = proto3.makeEnum(
  "ethereum.v1.outpost.Star.StarColor",
  [
    {no: 0, name: "COLOR_UNSPECIFIED"},
    {no: 1, name: "YELLOW"},
    {no: 2, name: "RED"},
    {no: 3, name: "GREEN"},
    {no: 4, name: "BLUE"},
  ],
);

