// @generated by protoc-gen-es v1.6.0
// @generated from file ethereum/v1/auth/auth.proto (package ethereum.v1.auth, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum ethereum.v1.auth.AccessLogType
 */
export const AccessLogType = proto3.makeEnum(
  "ethereum.v1.auth.AccessLogType",
  [
    {no: 0, name: "TYPE_UNSPECIFIED"},
    {no: 1, name: "SIGNIN"},
    {no: 2, name: "REFRESH"},
    {no: 3, name: "SIGNOUT"},
  ],
);

/**
 * @generated from message ethereum.v1.auth.SignInRequest
 */
export const SignInRequest = proto3.makeMessageType(
  "ethereum.v1.auth.SignInRequest",
  () => [
    { no: 1, name: "eoa_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "timestamp", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 3, name: "signature", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message ethereum.v1.auth.SignInResponse
 */
export const SignInResponse = proto3.makeMessageType(
  "ethereum.v1.auth.SignInResponse",
  () => [
    { no: 1, name: "access_tokens", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 2, name: "refresh_tokens", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
    { no: 3, name: "eoa_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "profiles", kind: "message", T: Profile, repeated: true },
    { no: 5, name: "has_accepted_terms", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message ethereum.v1.auth.Profile
 */
export const Profile = proto3.makeMessageType(
  "ethereum.v1.auth.Profile",
  () => [
    { no: 1, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "spaceship_addresses", kind: "scalar", T: 9 /* ScalarType.STRING */, repeated: true },
  ],
);

/**
 * @generated from message ethereum.v1.auth.RefreshTokenRequest
 */
export const RefreshTokenRequest = proto3.makeMessageType(
  "ethereum.v1.auth.RefreshTokenRequest",
  [],
);

/**
 * @generated from message ethereum.v1.auth.RefreshTokenResponse
 */
export const RefreshTokenResponse = proto3.makeMessageType(
  "ethereum.v1.auth.RefreshTokenResponse",
  () => [
    { no: 1, name: "access_token", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "refresh_token", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * @generated from message ethereum.v1.auth.SignoutRequest
 */
export const SignoutRequest = proto3.makeMessageType(
  "ethereum.v1.auth.SignoutRequest",
  [],
);

/**
 * @generated from message ethereum.v1.auth.SignoutResponse
 */
export const SignoutResponse = proto3.makeMessageType(
  "ethereum.v1.auth.SignoutResponse",
  [],
);

/**
 * @generated from message ethereum.v1.auth.SelectAccountRequest
 */
export const SelectAccountRequest = proto3.makeMessageType(
  "ethereum.v1.auth.SelectAccountRequest",
  () => [
    { no: 1, name: "spaceship_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message ethereum.v1.auth.SelectAccountResponse
 */
export const SelectAccountResponse = proto3.makeMessageType(
  "ethereum.v1.auth.SelectAccountResponse",
  () => [
    { no: 1, name: "access_token", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
    { no: 2, name: "refresh_token", kind: "scalar", T: 9 /* ScalarType.STRING */, opt: true },
  ],
);

/**
 * @generated from message ethereum.v1.auth.AcceptTermsOfServiceRequest
 */
export const AcceptTermsOfServiceRequest = proto3.makeMessageType(
  "ethereum.v1.auth.AcceptTermsOfServiceRequest",
  [],
);

/**
 * @generated from message ethereum.v1.auth.AuthenticateRequest
 */
export const AuthenticateRequest = proto3.makeMessageType(
  "ethereum.v1.auth.AuthenticateRequest",
  () => [
    { no: 1, name: "access_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message ethereum.v1.auth.AuthenticateResponse
 */
export const AuthenticateResponse = proto3.makeMessageType(
  "ethereum.v1.auth.AuthenticateResponse",
  () => [
    { no: 1, name: "eoa_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "profile_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "spaceship_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "has_accepted_terms", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

/**
 * @generated from message ethereum.v1.auth.GetTempTokenRequest
 */
export const GetTempTokenRequest = proto3.makeMessageType(
  "ethereum.v1.auth.GetTempTokenRequest",
  [],
);

/**
 * @generated from message ethereum.v1.auth.GetTempTokenResponse
 */
export const GetTempTokenResponse = proto3.makeMessageType(
  "ethereum.v1.auth.GetTempTokenResponse",
  () => [
    { no: 1, name: "access_token", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message ethereum.v1.auth.DownloadRequest
 */
export const DownloadRequest = proto3.makeMessageType(
  "ethereum.v1.auth.DownloadRequest",
  () => [
    { no: 1, name: "url", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message ethereum.v1.auth.DownloadResponse
 */
export const DownloadResponse = proto3.makeMessageType(
  "ethereum.v1.auth.DownloadResponse",
  () => [
    { no: 1, name: "header", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "body", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message ethereum.v1.auth.AccessTokenClaim
 */
export const AccessTokenClaim = proto3.makeMessageType(
  "ethereum.v1.auth.AccessTokenClaim",
  () => [
    { no: 1, name: "session_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "eoa_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "profile_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "spaceship_address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "has_accepted_terms", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
  ],
);

