// @generated by protoc-gen-es v1.6.0
// @generated from file blast/v1/user/backspace.proto (package blast.v1.user, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message blast.v1.user.GetBackspaceRequest
 */
export const GetBackspaceRequest = proto3.makeMessageType(
  "blast.v1.user.GetBackspaceRequest",
  () => [
    { no: 1, name: "user", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

/**
 * @generated from message blast.v1.user.UpdateBackspaceRequest
 */
export const UpdateBackspaceRequest = proto3.makeMessageType(
  "blast.v1.user.UpdateBackspaceRequest",
  () => [
    { no: 1, name: "backspace", kind: "message", T: Backspace },
  ],
);

/**
 * @generated from message blast.v1.user.Backspace
 */
export const Backspace = proto3.makeMessageType(
  "blast.v1.user.Backspace",
  () => [
    { no: 1, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "introduction_chat", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

