// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: ethereum/v1/profile/my_space.proto

/* eslint-disable */

export const protobufPackage = "ethereum.v1.profile";

/** MySpace message represents a profile's MySpace. */
export interface MySpace {
  /** The name of Profile of the MySpace */
  profile: string;
  /** The profile's assets. */
  assets:
    | Assets
    | undefined;
  /** The profile's StarDoodles. */
  starDoodles: StarDoodles | undefined;
}

/** Assets message represents a profile's assets. */
export interface Assets {
  /** The profile's Spaceships assets. */
  spaceships: SpaceshipAsset[];
  /** The profile's Badges assets. */
  badges: BadgeAsset[];
  /** The profile's Scores assets. */
  scores: ScoreAsset[];
  /** The profile's Alphabets assets. */
  alphabets: AlphabetAsset[];
  /** The profile's Blocks assets. */
  blocks: BlockAsset[];
}

/** SpaceshipReference message represents a Spaceship. */
export interface SpaceshipReference {
  /** The resource name of the Spaceship. */
  name: string;
  /** The nickname of the Spaceship. */
  nickname: string;
  /** The token_id of Spaceship NFT. */
  tokenId: string;
  /** The image uri of Spaceship NFT. */
  imageUri: string;
}

/** BadgeReference message represents a Badge. */
export interface BadgeReference {
  /** The resource name of the Badge. */
  name: string;
}

/** ScoreReference message represents a Score. */
export interface ScoreReference {
  /** The resource name of the Score. */
  name: string;
  /** The token_id of Score NFT. */
  tokenId: string;
  /** The image uri of Score NFT. */
  imageUri: string;
}

/** SpaceshipAsset message represents a Spaceship asset. */
export interface SpaceshipAsset {
  /** The ID of the Spaceship asset. */
  id: number;
  /** The URI of the Spaceship asset image. */
  imageUri: string;
  /** The position of the Spaceship asset. */
  position:
    | Position
    | undefined;
  /**
   * The timestamp of the Spaceship asset creation.
   * RFC3339 format e.g. "2006-01-02T15:04:05Z07:00"
   */
  createTime:
    | string
    | undefined;
  /**
   * The timestamp of the Spaceship asset update.
   * RFC3339 format e.g. "2006-01-02T15:04:05Z07:00"
   */
  updateTime:
    | string
    | undefined;
  /** The reference to the Spaceship. */
  reference: SpaceshipReference | undefined;
}

/** BadgeAsset message represents a Badge asset. */
export interface BadgeAsset {
  /** The ID of the Badge asset. */
  id: number;
  /** The URI of the Badge asset image. */
  imageUri: string;
  /** The position of the Badge asset. */
  position:
    | Position
    | undefined;
  /**
   * The timestamp of the Badge asset creation.
   * RFC3339 format e.g. "2006-01-02T15:04:05Z07:00"
   */
  createTime:
    | string
    | undefined;
  /**
   * The timestamp of the Badge asset update.
   * RFC3339 format e.g. "2006-01-02T15:04:05Z07:00"
   */
  updateTime:
    | string
    | undefined;
  /** The reference to the Badge. */
  reference: BadgeReference | undefined;
}

/** ScoreAsset message represents a Score asset. */
export interface ScoreAsset {
  /** The ID of the Score asset. */
  id: number;
  /** The URI of the Score asset image. */
  imageUri: string;
  /** The position of the Score asset. */
  position:
    | Position
    | undefined;
  /**
   * The timestamp of the Score asset creation.
   * RFC3339 format e.g. "2006-01-02T15:04:05Z07:00"
   */
  createTime:
    | string
    | undefined;
  /**
   * The timestamp of the Score asset update.
   * RFC3339 format e.g. "2006-01-02T15:04:05Z07:00"
   */
  updateTime:
    | string
    | undefined;
  /** The reference to the Score. */
  reference: ScoreReference | undefined;
}

/** AlphabetAsset message represents an Alphabet asset. */
export interface AlphabetAsset {
  /** The ID of the Alphabet asset. */
  id: number;
  /** The URI of the Alphabet asset image. */
  imageUri: string;
  /** The position of the Alphabet asset. */
  position:
    | Position
    | undefined;
  /**
   * The timestamp of the Alphabet asset creation.
   * RFC3339 format e.g. "2006-01-02T15:04:05Z07:00"
   */
  createTime:
    | string
    | undefined;
  /**
   * The timestamp of the Alphabet asset update.
   * RFC3339 format e.g. "2006-01-02T15:04:05Z07:00"
   */
  updateTime:
    | string
    | undefined;
  /** The character of the Alphabet asset. */
  character: number;
}

/** BlockAsset message represents a Block asset. */
export interface BlockAsset {
  /** The ID of the Block asset. */
  id: number;
  /** The URI of the Block asset image. */
  imageUri: string;
  /** The position of the Block asset. */
  position:
    | Position
    | undefined;
  /**
   * The timestamp of the Alphabet block creation.
   * RFC3339 format e.g. "2006-01-02T15:04:05Z07:00"
   */
  createTime:
    | string
    | undefined;
  /**
   * The timestamp of the Alphabet block update.
   * RFC3339 format e.g. "2006-01-02T15:04:05Z07:00"
   */
  updateTime: string | undefined;
}

/** StarDoodles message represents a profile's StarDoodles. */
export interface StarDoodles {
  /** The URI of the StarDoodles image. */
  imageUri: string;
  /** The positions of the StarDoodles. */
  positions: Position[];
}

/** Position message represents a position. */
export interface Position {
  /** The left position. */
  left: number;
  /** The top position. */
  top: number;
  /** The right position. */
  right: number;
  /** The bottom position. */
  bottom: number;
}
