// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.178.0
//   protoc               unknown
// source: ethereum/v1/profile/sns_connection.proto

/* eslint-disable */

export const protobufPackage = "ethereum.v1.profile";

/** SNSType enumeration represents the type of sns. */
export enum SNSType {
  /** SNS_UNSPECIFIED - Unspecified sns type. */
  SNS_UNSPECIFIED = "SNS_UNSPECIFIED",
  /** SNS_TWITTER - Twitter sns type. */
  SNS_TWITTER = "SNS_TWITTER",
}

/** ExternalProfile message represents an external profile. */
export interface ExternalProfile {
  /** The name of the external profile. */
  name: string;
  /** The image uri of the external profile. */
  imageUri: string;
  /** The link of the external profile. */
  link: string;
}

/** SNSConnection message represents a profile's connection. */
export interface SNSConnection {
  /** The profile resource name of the connection. */
  profile: string;
  /** The type of the SNS. */
  type: SNSType;
  /** The external profile. */
  externalProfile: ExternalProfile | undefined;
}
