// Code generated by protoc-gen-fake. DO NOT EDIT.

package notification

import (
	"github.com/ao-labs/protoc-gen-fake/pkg/fake"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// Default responses for NotificationService
var DefaultNotificationServiceResponses = map[string]fake.Response{
	"/ethereum.v1.notification.NotificationService/ListNotifications": {
		Method: "/ethereum.v1.notification.NotificationService/ListNotifications",
		Response: &ListNotificationsResponse{
			Notifications: nil,
			NextPageToken: "fake_NextPageToken",
		},
	},
	"/ethereum.v1.notification.NotificationService/AcknowledgeNotification": {
		Method:   "/ethereum.v1.notification.NotificationService/AcknowledgeNotification",
		Response: &emptypb.Empty{},
	},
	"/ethereum.v1.notification.NotificationService/CreateNotification": {
		Method: "/ethereum.v1.notification.NotificationService/CreateNotification",
		Response: &Notification{
			Name:       "fake_Name",
			Id:         42,
			Profile:    "fake_Profile",
			Type:       0,
			Action:     0,
			State:      0,
			Content:    nil,
			CreateTime: nil,
			Metadata:   nil,
		},
	},
}
